USE [master]
GO
/****** Object:  Database [ACADEMIA]    Script Date: 07/06/2025 10:17:50 ******/
CREATE DATABASE [ACADEMIA];
GO
ALTER DATABASE [ACADEMIA] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ACADEMIA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ACADEMIA] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ACADEMIA] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ACADEMIA] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ACADEMIA] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ACADEMIA] SET ARITHABORT OFF 
GO
ALTER DATABASE [ACADEMIA] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [ACADEMIA] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ACADEMIA] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ACADEMIA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ACADEMIA] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ACADEMIA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ACADEMIA] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ACADEMIA] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ACADEMIA] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ACADEMIA] SET  ENABLE_BROKER 
GO
ALTER DATABASE [ACADEMIA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ACADEMIA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ACADEMIA] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ACADEMIA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ACADEMIA] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ACADEMIA] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ACADEMIA] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ACADEMIA] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ACADEMIA] SET  MULTI_USER 
GO
ALTER DATABASE [ACADEMIA] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ACADEMIA] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ACADEMIA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ACADEMIA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ACADEMIA] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ACADEMIA] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'ACADEMIA', N'ON'
GO
ALTER DATABASE [ACADEMIA] SET QUERY_STORE = ON
GO
ALTER DATABASE [ACADEMIA] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [ACADEMIA]
GO
/****** Object:  Schema [desc]    Script Date: 07/06/2025 10:17:51 ******/
CREATE SCHEMA [desc]
GO
/****** Object:  Table [dbo].[Agendas]    Script Date: 07/06/2025 10:17:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Agendas](
	[cd_agenda] [int] IDENTITY(1,1) NOT NULL,
	[cd_aula] [int] NULL,
	[nm_aula] [varchar](30) NULL,
	[cd_aluno] [int] NULL,
	[cd_instrutor] [int] NULL,
	[dias_semana] [nvarchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[cd_agenda] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Aulas]    Script Date: 07/06/2025 10:17:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Aulas](
	[cd_aula] [int] IDENTITY(1,1) NOT NULL,
	[nm_aula] [nvarchar](255) NULL,
	[descricao] [varchar](max) NULL,
	[dt_inicio] [datetime] NULL,
	[dt_fim] [datetime] NULL,
	[cd_instrutor] [int] NULL,
	[capacidade] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[cd_aula] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Clientes]    Script Date: 07/06/2025 10:17:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Clientes](
	[cd_cliente] [int] IDENTITY(1,1) NOT NULL,
	[nm_cliente] [varchar](80) NULL,
	[cpf] [varchar](11) NOT NULL,
	[email] [varchar](80) NULL,
	[telefone] [varchar](11) NULL,
	[dt_nascimento] [date] NULL,
	[endereco] [varchar](max) NULL,
	[dt_cadastro] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[cd_cliente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[cpf] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Contratos]    Script Date: 07/06/2025 10:17:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Contratos](
	[cd_contrato] [int] IDENTITY(1,1) NOT NULL,
	[cd_funcionario] [int] NULL,
	[cd_cliente] [int] NULL,
	[cd_plano] [int] NULL,
	[dt_inicio] [date] NULL,
	[dt_fim] [date] NULL,
	[status] [nvarchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[cd_contrato] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Controle_Acessos]    Script Date: 07/06/2025 10:17:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Controle_Acessos](
	[cd_acesso] [int] IDENTITY(1,1) NOT NULL,
	[cd_cliente] [int] NULL,
	[dt_entrada] [datetime] NULL,
	[dt_saida] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[cd_acesso] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Funcionarios]    Script Date: 07/06/2025 10:17:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Funcionarios](
	[cd_funcionario] [int] IDENTITY(1,1) NOT NULL,
	[nm_funcionario] [varchar](80) NULL,
	[cpf] [varchar](11) NULL,
	[email] [varchar](80) NULL,
	[telefone] [varchar](11) NULL,
	[cd_cargo] [int] NULL,
	[nm_cargo] [varchar](90) NULL,
	[dt_admissao] [date] NULL,
	[dt_demissao] [date] NULL,
	[dt_afastamento] [date] NULL,
	[dt_retorno] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[cd_funcionario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[cpf] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Pagamentos]    Script Date: 07/06/2025 10:17:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Pagamentos](
	[cd_pagamento] [int] IDENTITY(1,1) NOT NULL,
	[cd_contrato] [int] NULL,
	[valor_pago] [decimal](32, 2) NULL,
	[metodo_pag] [nvarchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[cd_pagamento] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Planos]    Script Date: 07/06/2025 10:17:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Planos](
	[cd_plano] [int] IDENTITY(1,1) NOT NULL,
	[nm_plano] [varchar](80) NULL,
	[descricao] [varchar](max) NULL,
	[vl_preco] [decimal](32, 2) NULL,
	[tp_plano] [nvarchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[cd_plano] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Agendas]  WITH CHECK ADD FOREIGN KEY([cd_aluno])
REFERENCES [dbo].[Clientes] ([cd_cliente])
GO
ALTER TABLE [dbo].[Agendas]  WITH CHECK ADD FOREIGN KEY([cd_aula])
REFERENCES [dbo].[Aulas] ([cd_aula])
GO
ALTER TABLE [dbo].[Aulas]  WITH CHECK ADD FOREIGN KEY([cd_instrutor])
REFERENCES [dbo].[Funcionarios] ([cd_funcionario])
GO
ALTER TABLE [dbo].[Contratos]  WITH CHECK ADD FOREIGN KEY([cd_cliente])
REFERENCES [dbo].[Clientes] ([cd_cliente])
GO
ALTER TABLE [dbo].[Contratos]  WITH CHECK ADD FOREIGN KEY([cd_funcionario])
REFERENCES [dbo].[Funcionarios] ([cd_funcionario])
GO
ALTER TABLE [dbo].[Contratos]  WITH CHECK ADD FOREIGN KEY([cd_plano])
REFERENCES [dbo].[Planos] ([cd_plano])
GO
ALTER TABLE [dbo].[Controle_Acessos]  WITH CHECK ADD FOREIGN KEY([cd_cliente])
REFERENCES [dbo].[Clientes] ([cd_cliente])
GO
ALTER TABLE [dbo].[Pagamentos]  WITH CHECK ADD FOREIGN KEY([cd_contrato])
REFERENCES [dbo].[Contratos] ([cd_contrato])
GO
ALTER TABLE [dbo].[Agendas]  WITH CHECK ADD CHECK  (([dias_semana]='DOMINGO' OR [dias_semana]='SABADO' OR [dias_semana]='SEXTA' OR [dias_semana]='QUINTA' OR [dias_semana]='QUARTA' OR [dias_semana]='TERÇA' OR [dias_semana]='SEGUNDA'))
GO
ALTER TABLE [dbo].[Contratos]  WITH CHECK ADD CHECK  (([status]='ATIVO' OR [status]='INATIVO' OR [status]='PENDENTE'))
GO
ALTER TABLE [dbo].[Pagamentos]  WITH CHECK ADD CHECK  (([metodo_pag]='DINHEIRO' OR [metodo_pag]='PIX' OR [metodo_pag]='CREDITO' OR [metodo_pag]='DEBITO'))
GO
ALTER TABLE [dbo].[Planos]  WITH CHECK ADD CHECK  (([tp_plano]='BLACK' OR [tp_plano]='GOLD' OR [tp_plano]='STANDART'))
GO
USE [master]
GO
ALTER DATABASE [ACADEMIA] SET  READ_WRITE 
GO
